export const SIGN_IN_WITH_EMAIL = 'auth/SIGN_IN_WITH_EMAIL';
export const SIGN_IN_WITH_EMAIL_SUCCESS = 'auth/SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_IN_WITH_EMAIL_ERROR = 'auth/SIGN_IN_WITH_EMAIL_ERROR';

export const SIGN_UP_WITH_EMAIL = 'auth/SIGN_UP_WITH_EMAIL';
export const SIGN_UP_WITH_EMAIL_SUCCESS = 'auth/SIGN_UP_WITH_EMAIL_SUCCESS';
export const SIGN_UP_WITH_EMAIL_ERROR = 'auth/SIGN_UP_WITH_EMAIL_ERROR';

export const SIGN_IN_WITH_MOBILE = 'auth/SIGN_IN_WITH_MOBILE';
export const SIGN_IN_WITH_MOBILE_ERROR = 'auth/SIGN_IN_WITH_MOBILE_ERROR';

export const SIGN_IN_WITH_GOOGLE = 'auth/SIGN_IN_WITH_GOOGLE';
export const SIGN_IN_WITH_GOOGLE_ERROR = 'auth/SIGN_IN_WITH_GOOGLE_ERROR';
export const SIGN_IN_WITH_GOOGLE_CANCEL = 'auth/SIGN_IN_WITH_GOOGLE_CANCEL';

export const UPDATE_LOCATION = 'auth/UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS = 'auth/UPDATE_LOCATION_SUCCESS';

export const SIGN_IN_WITH_FACEBOOK = 'auth/SIGN_IN_WITH_FACEBOOK';
export const SIGN_IN_WITH_FACEBOOK_ERROR = 'auth/SIGN_IN_WITH_FACEBOOK_ERROR';
export const SIGN_IN_WITH_FACEBOOK_CANCEL = 'auth/SIGN_IN_WITH_FACEBOOK_CANCEL';

export const SIGN_IN_WITH_APPLE = 'auth/SIGN_IN_WITH_APPLE';
export const SIGN_IN_WITH_APPLE_ERROR = 'auth/SIGN_IN_WITH_APPLE_ERROR';
export const SIGN_IN_WITH_APPLE_CANCEL = 'auth/SIGN_IN_WITH_APPLE_CANCEL';

export const FORGOT_PASSWORD = 'auth/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'auth/FORGOT_PASSWORD_ERROR';

export const CHECK_AUTH = 'auth/CHECK_AUTH';

export const SIGN_OUT = 'auth/SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'auth/SIGN_OUT_SUCCESS';

export const CHANGE_EMAIL = 'auth/CHANGE_EMAIL';
export const CHANGE_EMAIL_SUCCESS = 'auth/CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_ERROR = 'auth/CHANGE_EMAIL_ERROR';

export const CHANGE_PASSWORD = 'auth/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'auth/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'auth/CHANGE_PASSWORD_ERROR';

export const GET_CUSTOMER = 'auth/GET_CUSTOMER';
export const GET_CUSTOMER_SUCCESS = 'auth/GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_ERROR = 'auth/GET_SHIPPING_ADDRESS_ERROR';

export const UPDATE_SHIPPING_ADDRESS_SUCCESS =
  'auth/UPDATE_SHIPPING_ADDRESS_SUCCESS';

export const UPDATE_CUSTOMER = 'auth/UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'auth/UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'auth/UPDATE_CUSTOMER_ERROR';

export const UPDATE_USER_SUCCESS = 'auth/UPDATE_USER_SUCCESS';

export const SIGN_UP_WITH_OTP = 'auth/SIGN_UP_WITH_OTP';
export const SIGN_UP_WITH_OTP_SUCCESS = 'auth/SIGN_UP_WITH_OTP_SUCCESS';
export const SIGN_UP_WITH_OTP_ERROR = 'auth/SIGN_UP_WITH_OTP_ERROR';

export const SIGN_IN_WITH_OTP = 'auth/SIGN_IN_WITH_OTP';
export const SIGN_IN_WITH_OTP_SUCCESS = 'auth/SIGN_IN_WITH_OTP_SUCCESS';
export const SIGN_IN_WITH_OTP_ERROR = 'auth/SIGN_IN_WITH_OTP_ERROR';

export const IS_LOGIN = 'auth/IS_LOGIN';

export const CHANGE_DATA = 'auth/CHANGE_DATA';
