export const UPDATE_ORDER_REVIEW = 'checkout/UPDATE_ORDER_REVIEW';
export const UPDATE_ORDER_REVIEW_SUCCESS =
  'checkout/UPDATE_ORDER_REVIEW_SUCCESS';
export const UPDATE_ORDER_REVIEW_ERROR = 'checkout/UPDATE_ORDER_REVIEW_ERROR';

export const GET_SHIPPING_METHODS = 'checkout/GET_SHIPPING_METHODS';
export const GET_SHIPPING_METHODS_SUCCESS =
  'checkout/GET_SHIPPING_METHODS_SUCCESS';
export const GET_SHIPPING_METHODS_ERROR = 'checkout/GET_SHIPPING_METHODS_ERROR';

export const CHECKOUT = 'checkout/CHECKOUT';
export const CHECKOUT_SUCCESS = 'checkout/CHECKOUT_SUCCESS';
export const CHECKOUT_ERROR = 'checkout/CHECKOUT_METHODS_ERROR';

export const UPDATE_DATA = 'checkout/UPDATE_DATA';
